#!/usr/bin/env python3
import rospy
from qt_action_executor_wrapper.qt_action_executor_wrapper import QtActionExecutorWrapper

if __name__ == '__main__':
    rospy.init_node('qt_action_executor')
    qt_action_executor = QtActionExecutorWrapper()
    try:
        while not rospy.is_shutdown():
            qt_action_executor.act()
            rospy.sleep(5)
    except rospy.ROSInterruptException as exc:
        print('qt_action_executor ...')
